INSERT INTO DELI_ZALIHE VALUES (1, 2);
INSERT INTO DELI_ZALIHE VALUES (1, 5);
INSERT INTO DELI_ZALIHE VALUES (2, 3);
INSERT INTO DELI_ZALIHE VALUES (3, 1);
INSERT INTO DELI_ZALIHE VALUES (4, 2);
INSERT INTO DELI_ZALIHE VALUES (5, 4);