CREATE TABLE DONOR (
    LICNO_IME VARCHAR2(20) NOT NULL,
    PREZIME VARCHAR2(20) NOT NULL,
    ADRESA VARCHAR2(50),
    JMBG NUMBER(13),
    GOD_RODJ NUMBER(4) NOT NULL,
    KRVNA_GRUPA VARCHAR2(2) NOT NULL,
    RH_FAKTOR VARCHAR2(1) NOT NULL,
    POL VARCHAR2(1) NOT NULL,
    TEZINA NUMBER(3) NOT NULL,
    CONSTRAINT DONOR_PK PRIMARY KEY(JMBG),
    CONSTRAINT GOD_RODJ_CK CHECK (GOD_RODJ BETWEEN 1955 AND 2005),
    CONSTRAINT KRVNA_GRUPA_CK CHECK (KRVNA_GRUPA IN ('0', 'A', 'B', 'AB')),
    CONSTRAINT RH_FAKTOR_CK CHECK (RH_FAKTOR IN ('+', '-')),
    CONSTRAINT POL_CK CHECK (POL IN ('M', 'Z')),
    CONSTRAINT CHECK TEZINA_CK (TEZINA > 50)
);

ALTER TABLE DONOR RENAME CONSTRAINT KRVNA_GRUPA_CK TO DON_KRVNA_GRUPA_CK;
ALTER TABLE DONOR RENAME CONSTRAINT RH_FAKTOR_CK TO DON_RH_FAKTOR_CK;
ALTER TABLE DONOR RENAME CONSTRAINT POL_CK TO DON_POL_CK;

CREATE TABLE BANKA_KRVI (
    ID_BANKE NUMBER(5),
    NAZIV VARCHAR2(50) NOT NULL,
    LOKACIJA VARCHAR2(20) NOT NULL,
    KONTAKT_TELEFON VARCHAR2(10) NOT NULL,
    CONSTRAINT BANKA_KRVI_PK PRIMARY KEY(ID_BANKE),
    CONSTRAINT NAZ_LOK_UNIQUE UNIQUE (NAZIV, LOKACIJA),
    CONSTRAINT KONTAKT_TEL_UNIQUE UNIQUE (KONTAKT_TELEFON)
);

ALTER TABLE BANKA_KRVI RENAME CONSTRAINT NAZ_LOK_UNIQUE TO BK_NAZ_LOK;

CREATE TABLE ZDRAVSTVENA_USTANOVA (
    ID_USTANOVE NUMBER(5),
    NAZIV VARCHAR2(50) NOT NULL,
    LOKACIJA VARCHAR2(20) NOT NULL,
    TIP VARCHAR2(26),
    CONSTRAINT ZDRAVSTVENA_USTANOVA_PK PRIMARY KEY(ID_USTANOVE),
    CONSTRAINT ZU_NAZ_LOK_UNIQUE UNIQUE (NAZIV, LOKACIJA),
    CONSTRAINT TIP_CK CHECK (TIP IN ('opsta bolnica', 'vojnomedicinska bolnica', 'klinika za kardiohirurgiju'))
);

CREATE TABLE PACIJENT (
    IME VARCHAR2(40) NOT NULL,
    ADRESA VARCHAR2(50),
    JMBG NUMBER(13),
    KRVNA_GRUPA VARCHAR2(2) NOT NULL,
    RH_FAKTOR VARCHAR2(1) NOT NULL,
    POL VARCHAR2(1) NOT NULL,
    ID_USTANOVE NUMBER(5) NOT NULL,
    DAT_POCETKA_LECENJA DATE,
    CONSTRAINT PACIJENT_PK PRIMARY KEY (JMBG),
    CONSTRAINT PAC_KRVNA_GRUPA_CK CHECK (KRVNA_GRUPA IN ('0', 'A', 'B', 'AB')),
    CONSTRAINT PAC_FAKTOR_CK CHECK (RH_FAKTOR IN ('+', '-')),
    CONSTRAINT PAC_POL_CK CHECK (POL IN ('M', 'Z')),
    CONSTRAINT PACIJENT_FK FOREIGN KEY(ID_USTANOVE) REFERENCES ZDRAVSTVENA_USTANOVA
);

CREATE TABLE DONACIJA (
    MBR_DONORA NUMBER(13),
    RBR_DONACIJE NUMBER(3),
    DATUM_DONACIJE DATE NOT NULL,
    KOLICINA NUMBER(3) NOT NULL,
    ID_BANKE NUMBER(5) NOT NULL,
    STATUS VARCHAR2(11) NOT NULL,
    CONSTRAINT DONACIJA_FK_DONOR FOREIGN KEY(MBR_DONORA) REFERENCES DONOR(JMBG),
    CONSTRAINT RBR_DONACIJE_CK CHECK (RBR_DONACIJE > 0),
    CONSTRAINT DONACIJA_PK PRIMARY KEY(MBR_DONORA, RBR_DONACIJE),
    CONSTRAINT KOLICINA_CK CHECK(KOLICINA BETWEEN 250 AND 450),
    CONSTRAINT DONACIJA_FK_BANKA FOREIGN KEY(ID_BANKE) REFERENCES BANKA_KRVI,
    CONSTRAINT STATUS_CK CHECK (STATUS IN ('na stanju', 'iskoriscena'))
);

ALTER TABLE DONACIJA MODIFY (KOLICINA DEFAULT 350);

CREATE TABLE SNABDEVA (
    ID_BANKE NUMBER(5),
    ID_USTANOVE NUMBER(5),
    CONSTRAINT SNABDEVA_FK_BANKA FOREIGN KEY(ID_BANKE) REFERENCES BANKA_KRVI,
    CONSTRAINT SNABDEVA_FK_USTANOVA FOREIGN KEY(ID_USTANOVE) REFERENCES ZDRAVSTVENA_USTANOVA,
    CONSTRAINT SNABDEVA_PK PRIMARY KEY(ID_BANKE, ID_USTANOVE)
);

CREATE TABLE DELI_ZALIHE (
    ID_BANKE_D NUMBER(5), /*BANKA KOJA DELI ZALIHE*/
    ID_BANKE_K NUMBER(5), /*BANKA KOJA KORISTI DELJENE ZALIHE*/
    CONSTRAINT DELI_ZALIHE_FK_D FOREIGN KEY(ID_BANKE_D) REFERENCES BANKA_KRVI,
    CONSTRAINT DELI_ZALIHE_FK_K FOREIGN KEY(ID_BANKE_K) REFERENCES BANKA_KRVI,
    CONSTRAINT DELI_ZALIHE_PK PRIMARY KEY(ID_BANKE_D, ID_BANKE_K)
);

CREATE TABLE DON_MAIL (
    MBR_DONORA NUMBER(13),
    EMAIL VARCHAR2(30),
    CONSTRAINT DON_MAIL_FK FOREIGN KEY(MBR_DONORA) REFERENCES DONOR,
    CONSTRAINT DON_MAIL_PK PRIMARY KEY(MBR_DONORA, EMAIL)
);

CREATE TABLE DON_TEL (
    MBR_DONORA NUMBER(13),
    TELEFON VARCHAR2(10),
    CONSTRAINT DON_TEL_FK FOREIGN KEY(MBR_DONORA) REFERENCES DONOR,
    CONSTRAINT DON_TEL_PK PRIMARY KEY(MBR_DONORA, TELEFON)
);

CREATE TABLE PACIJENT_KONTAKT (
    MBR_PACIJENTA NUMBER(13),
    TELEFON VARCHAR2(10),
    CONSTRAINT PACIJENT_KONTAKT_FK FOREIGN KEY(MBR_PACIJENTA) REFERENCES PACIJENT,
    CONSTRAINT PACIJENT_KONTAKT_PK PRIMARY KEY(MBR_PACIJENTA, TELEFON)
);